server:
  port: 9000

spring:
  data:
    mongodb:
      host: bloger-mongo
      username: bloger
      password: bloger
      authentication-database: admin
      database: bloger

logging:
  level:
    me.lee.bloger: warn

jwt:
  secret: yourcustomjwtsecretkey